defmodule PropertyDamage.Export.ExUnit do
  @moduledoc false

  alias PropertyDamage.Export.Common
  alias PropertyDamage.FailureReport

  @doc """
  Generates an ExUnit test module from a failure report.

  ## Options

  - `:module_name` - Module name for the test (optional, auto-generated)
  - `:model` - Model module to use (falls back to report.model)
  - `:adapter` - Adapter module to use (falls back to report.adapter)
  - `:adapter_config` - Adapter configuration map (optional)
  - `:test_name` - Custom test name (optional)
  - `:expect_fixed` - If true, expect the test to pass (default: false)
  """
  @spec generate(FailureReport.t(), keyword()) :: String.t()
  def generate(%FailureReport{} = report, opts \\ []) do
    metadata = Common.extract_metadata(report)
    model = Keyword.get(opts, :model, metadata.model)
    adapter = Keyword.get(opts, :adapter, metadata.adapter)

    module_name = Keyword.get(opts, :module_name, generate_module_name(metadata))
    test_name = Keyword.get(opts, :test_name, generate_test_name(metadata))
    adapter_config = Keyword.get(opts, :adapter_config)
    expect_fixed = Keyword.get(opts, :expect_fixed, false)

    [
      generate_moduledoc(metadata),
      generate_module_header(module_name, model, adapter),
      generate_test(report, test_name, model, adapter, adapter_config, expect_fixed),
      generate_module_footer()
    ]
    |> Enum.join("\n")
  end

  # ============================================================================
  # Module Structure
  # ============================================================================

  defp generate_moduledoc(metadata) do
    failure_desc =
      case metadata.check_name do
        nil -> to_string(metadata.failure_type)
        check -> "#{check} check failed"
      end

    timestamp =
      case metadata.timestamp do
        %DateTime{} = dt -> DateTime.to_date(dt) |> Date.to_string()
        _ -> Date.utc_today() |> Date.to_string()
      end

    """
    # Regression test generated by PropertyDamage
    # Failure: #{failure_desc}
    # Date: #{timestamp}
    # Seed: #{metadata.seed}
    """
  end

  defp generate_module_header(module_name, model, adapter) do
    model_str = if model, do: inspect(model), else: "YourModel"
    adapter_str = if adapter, do: inspect(adapter), else: "YourAdapter"

    """
    defmodule #{inspect(module_name)} do
      @moduledoc \"\"\"
      Regression test to prevent reintroduction of a previously found bug.

      This test reproduces a failure found by PropertyDamage.
      If the bug is fixed, the test will pass. If the bug reappears, it will fail.
      \"\"\"
      use ExUnit.Case, async: true

      alias #{model_str}, as: Model
      alias #{adapter_str}, as: Adapter
    """
  end

  defp generate_test(report, test_name, model, adapter, adapter_config, expect_fixed) do
    seed = report.seed
    commands_code = generate_commands_code(report)
    run_opts = generate_run_opts(model, adapter, adapter_config, seed)

    assertion =
      if expect_fixed do
        generate_expect_pass_assertion()
      else
        generate_expect_fail_assertion(report)
      end

    """
      @tag :regression
      @tag seed: #{seed}
      test "#{test_name}" do
        # Shrunk command sequence that triggers the failure
    #{commands_code}

        # Run with the exact seed for deterministic reproduction
        result = PropertyDamage.run(#{run_opts})

    #{assertion}
      end
    """
  end

  defp generate_module_footer do
    "end\n"
  end

  # ============================================================================
  # Commands Generation
  # ============================================================================

  defp generate_commands_code(report) do
    command_strs =
      report
      |> FailureReport.steps()
      |> Enum.map_join(",\n", fn step ->
        case step.label do
          label when is_binary(label) -> "      # #{label}\n#{format_command(step.command)}"
          _ -> format_command(step.command)
        end
      end)

    # Bound with a leading underscore: the regression test reproduces the
    # failure by re-running with the exact seed (max_runs: 1), so this list is
    # documentation of the shrunk sequence, not executed. Naming it `commands`
    # made every generated test fail `--warnings-as-errors` (unused variable).
    """
        _commands = [
    #{command_strs}
        ]
    """
  end

  defp format_command(command) do
    module = command.__struct__
    fields = Map.from_struct(command)

    if map_size(fields) == 0 do
      "      %#{inspect(module)}{}"
    else
      field_strs =
        fields
        |> Enum.map_join(", ", fn {k, v} -> "#{k}: #{format_field_value(v)}" end)

      "      %#{inspect(module)}{#{field_strs}}"
    end
  end

  # Note: is_atom also covers booleans and nil, which inspect correctly
  defp format_field_value(value) when is_atom(value), do: inspect(value)
  defp format_field_value(value) when is_binary(value), do: inspect(value)
  defp format_field_value(value) when is_number(value), do: inspect(value)

  defp format_field_value(value) when is_list(value) do
    items = Enum.map_join(value, ", ", &format_field_value/1)
    "[#{items}]"
  end

  defp format_field_value(value) when is_map(value) do
    if struct_value?(value) do
      format_command(value)
    else
      items =
        Enum.map_join(value, ", ", fn {k, v} ->
          "#{format_map_key(k)} => #{format_field_value(v)}"
        end)

      "%{#{items}}"
    end
  end

  # PIDs/references/functions/ports have no valid source literal; inspect/1
  # renders them as `#PID<...>` etc., which is a syntax error in generated code.
  defp format_field_value(value)
       when is_pid(value) or is_reference(value) or is_function(value) or is_port(value),
       do: "nil"

  defp format_field_value(value) do
    inspected = inspect(value)
    # Any other `#...`-prefixed inspect output (e.g. a struct with a custom
    # Inspect impl) is not a valid literal either; fall back to something that
    # compiles rather than emitting un-parseable code.
    if String.starts_with?(inspected, "#"), do: "nil", else: inspected
  end

  defp format_map_key(key) when is_atom(key), do: inspect(key)
  defp format_map_key(key), do: inspect(key)

  defp struct_value?(%{__struct__: _}), do: true
  defp struct_value?(_), do: false

  # ============================================================================
  # Run Options
  # ============================================================================

  defp generate_run_opts(_model, _adapter, adapter_config, seed) do
    opts = [
      "model: Model",
      "adapter: Adapter",
      "seed: #{seed}",
      "max_runs: 1"
    ]

    opts =
      if adapter_config do
        opts ++ ["adapter_config: #{inspect(adapter_config)}"]
      else
        opts
      end

    Enum.join(opts, ",\n          ")
  end

  # ============================================================================
  # Assertions
  # ============================================================================

  defp generate_expect_pass_assertion do
    """
        # Expect the bug to be fixed (test passes)
        case result do
          {:ok, _stats} ->
            :ok

          {:error, failure} ->
            flunk(\"\"\"
            Bug has resurfaced!

            Expected the bug to be fixed, but PropertyDamage found a failure:
            \#{PropertyDamage.FailureReport.failure_message(failure)}

            Seed: \#{failure.seed}
            \"\"\")
        end
    """
  end

  defp generate_expect_fail_assertion(report) do
    failure_type = FailureReport.failure_type(report)

    check_match =
      case FailureReport.check_name(report) do
        nil ->
          ""

        check ->
          "\n          assert PropertyDamage.FailureReport.check_name(failure) == #{inspect(check)}"
      end

    """
        # Expect the bug to still be present (confirms reproduction)
        case result do
          {:ok, _stats} ->
            # Bug is fixed! Update this test to expect_fixed: true
            IO.puts("Note: Bug appears to be fixed. Consider updating test.")
            :ok

          {:error, failure} ->
            # Confirm we get the same type of failure
            assert PropertyDamage.FailureReport.failure_type(failure) == #{inspect(failure_type)}#{check_match}
        end
    """
  end

  # ============================================================================
  # Name Generation
  # ============================================================================

  defp generate_module_name(metadata) do
    Module.concat([Regressions, :"Seed#{metadata.seed}Test"])
  end

  defp generate_test_name(metadata) do
    case metadata.check_name do
      nil -> "reproduces #{metadata.failure_type} failure (seed #{metadata.seed})"
      check -> "reproduces #{check} violation (seed #{metadata.seed})"
    end
  end
end
